### ISSUE TITLE
kojiweb: format task parameters

### ISSUE THREAD

**Issue by pbabinca** [release-engineering/koji-containerbuild#1]
Modify kojiweb templates to format task parameters.

Templates in koji repository are easy to modify. The problem is that koji's template system isn't pluggable/extensible by the koji plugins.

**Comment by pbabinca** [comment]
Currently parameters of tasks created by koji-containerbuild are just pretty-formatted python's dicts and lists:

`Parameters 	['git://foo.bar/rpms/rhmap-fh-mbaas-docker#783beabedf63487241d06f5f88159a739e5ef5d2', 'my-nice-product-4.0-rhel-7-docker-candidate', {'scratch': False}] `

Other tasks formats parameters with the key names, like:

```
Parameters: 	Arches: x86_64
                        Build Target: foo-rhel-6.7-docker
                        Installation Tree: http://foo.bar/rel-eng/updates/RHEL-6.7-20380119.0/compose/Server/x86_64/os
Options:
  kickstart = rhel-6.7-server-docker.ks
  disk_size = 10
  ksversion = RHEL7
  format = docker
  ksurl = git://bar.foo/kickstarts.git?rhel6#HEAD
  distro = RHEL-6.7


```

**Comment by vrutkovs** [comment]
It seems to be hard-coded in koji and task-specific: https://github.com/koji-project/koji/blob/547d7ee63fdbac89efa311e5af4d2165dc29ca9a/cli/koji#L4253

**Comment by pbabinca** [comment]
@vrutkovsk that was my last sentence about. Even though koji has plugins it doesn't have a way to extend templates by plugins.

**Comment by vrutkovs** [comment]
Koji issue: https://fedorahosted.org/koji/ticket/330
Pagure PR: https://pagure.io/koji/pull-request/82

**Comment by twaugh** [comment]
Also related: https://pagure.io/koji/issue/193

Closing this until there is better Koji support for plugins using kojiweb.
