### ISSUE TITLE
Cannot rebuild failed build if last build's parent failed

### ISSUE THREAD

**Issue by ppisar** [release-engineering/koji-containerbuild#14]
After some glitches in OSBS, koji retrieved image tar ball and marked parent task as failed. After fixing OSBS, I tried to rebuild the container again, OSBS succeeded, but koji protested that the container tar archive already exists:

GenericError: Error importing build log. /mnt/brew/packages/rh-perl520-docker/5.20/4/data/logs/image/openshift-final.log already exists.

Koji should deal with it to allow respinning  failed builds as it can be done with RPM packages.

**Comment by twaugh** [comment]
This issue seems to be from before Content Generator imports -- the structure of koji-containerbuild and OSBS builds has changed significantly.
Please re-open if you see this issue still.
