### ISSUE TITLE
Docs request: Security guide

### ISSUE THREAD

**Issue by maxamillion** [release-engineering/koji-containerbuild#16]
I would like the request documentation on how to configure koji-containerbuild with an OSBS environment such that their communications are kept secure. Also, if there are other general security concerns it would be nice for them to be documented as well.

Thank you,
-AdamM

**Comment by pbabinca** [comment]
koji-containerbuild plugin accesses OSBS similarly as any other client with osbs-client. I know we've tested only one setup for Kerberos authentication - using proxy as it is [documented in deployment guide](https://github.com/projectatomic/osbs-client/blob/master/docs/osbs_instance_setup.md#authentication-and-authorization). [Upstream has documentation](https://docs.openshift.org/latest/install_config/configuring_authentication.html#RequestHeaderIdentityProvider) for other types of authentications.

**Comment by lcarva** [comment]
Addressed by comment above.
