### ISSUE TITLE
Improve error message about unknown rpm

### ISSUE THREAD

**Issue by pbabinca** [release-engineering/koji-containerbuild#17]
Currently if the plugin doesn't find an rpm it fails with the non user friendly error message:

> GenericError:
> No such rpm: {'name': 'percona-release', 'sigmd5': '5aa504c1068ad4d92b19ef93f0bb5703', 'buildtime': 1411373342, 'epoch': None, 'version': '0.1', 'release': '3', 'arch': 'noarch', 'size': 5921}

Improve it by nice printing of the rpm and the reason what happened. Maybe something like:

> percona-release-0.1-3.noarch.rpm wasn't found in the (koji) buildystem. Containers can contain only > packages which are known by the buildsystem.

**Comment by lcarva** [comment]
This relates to workflow prior to content generator.
