### ISSUE TITLE
Create global log

### ISSUE THREAD

**Issue by pbabinca** [release-engineering/koji-containerbuild#19]
Some parts of the build process cannot be easily followed. E.g. progress of point 5 https://github.com/release-engineering/koji-containerbuild/blob/develop/docs/build-process.md or if the parent build process was forcefully killed. Create overall log where the overall process will be logged - what is going to be next and when it finish.

**Comment by lcarva** [comment]
osbs-client.log should give an overview: https://github.com/release-engineering/koji-containerbuild/pull/80
