### ISSUE TITLE
Disable scratch builds until a proper solution is found

### ISSUE THREAD

**Issue by vrutkovs** [release-engineering/koji-containerbuild#51]
Currently scratch builds are overwriting the normal builds, so we should disallow scratch builds and output a warning for now

**Comment by pbabinca** [comment]
Wouldn't be better to implement scratch build as a part of the process?

**Comment by hhorak** [comment]
@pbabinca if you can make it happen very soon, then why not, but I'd prefer to disable it asap since the current behavior can cause real troubles (see rhbz1349312).

**Comment by vrutkovs** [comment]
Scratch builds are now working correctly - see #54
