### ISSUE TITLE
is this deprecated?

### ISSUE THREAD

**Issue by ktdreyer** [release-engineering/koji-containerbuild#69]
Is this software deprecated now that we're using https://github.com/projectatomic/atomic-reactor ?

**Comment by lcarva** [comment]
No. It's still used. koji-containerbuild is the glue that makes koji interact with an OpenShift cluster to build container images.
The actual process of building the container image is still performed by atomic-reactor.

**Comment by twaugh** [comment]
This could be made clearer in http://osbs.readthedocs.io/en/latest/users.html#understanding-the-build-process
