### ISSUE TITLE
Auto populate the container version based on a "primary rpm" version

### ISSUE THREAD

**Issue by cverna** [release-engineering/koji-containerbuild#95]
In Fedora we would like to automatically version our containers based on a "primary rpm". We have a couple of ticket open on this subject [0][1].

The current idea to implement this feature is to use a new optional LABEL in the Dockerfile, for example `version.rpm`. Then some logic would be added to koji-containerbuild to use the rpm defined in this LABEL to query koji using the `getLatestBuild` method. The result of the query would be used to populate the VERSION LABEL of the container.

I open this ticket to start the discussion on the implementation of this feature.

[0] - https://pagure.io/atomic-wg/issue/254
[1] - https://pagure.io/atomic-wg/issue/249

**Comment by lcarva** [comment]
Thanks for opening this. It does sound like something that would be useful to many use cases.

The initial problem I see is that if `version.rpm` points to an rpm that is not coming from a koji repo, for example. The info returned by `getLatestBuild` would be incorrect. But I guess we can validate after image is built that the version of installed rpm is as expected.

**Comment by cverna** [comment]
As discussed this seems that it would be easier to do on atomic-reactor. I ll open an issue there and then close this one.

**Comment by TomasTomecek** [comment]
+1 on doing this in a-r as a post build action

One question: should the value be just the content of the version rpm macro? should there be some more processing? i.e. regex

**Comment by cverna** [comment]
I have opened https://github.com/projectatomic/atomic-reactor/issues/963 to continue the discussion there.
@TomasTomecek 
> +1 on doing this in a-r as a post build action

I was thinking that this would need to be a pre build plugin since it needs to modify the Dockerfile. Can you confirm ? or explain why it should be post build ?

> One question: should the value be just the content of the version rpm macro? should there be some more processing? i.e. regex

To start with I would just use the content of the version rpm macro. But If use cases are there I don't think it should be too hard to add support for some processing.
